config/routes.rb
Rails.application.routes.draw do

  root    "home#index"
  get     "about"       => "home#about", as: "about"
  get     "words"       => "words#index", as: "words"
  get     "signup"      => "users#new"
  get     "login"       => "sessions#new"
  get     "/results/:id", to: "results#show", as: "result"
  post    "login"       => "sessions#create"
  delete  "logout"      => "sessions#destroy"

  resources :users do
    member do
      resources :relationships, only: [:index, :create, :destroy]
    end
  end
  resources :categories
  resources :lessons
  resources :lesson_words
  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :words
    resources :answers
    resources :users
  end

end

app/models/word.rb
class Word < ActiveRecord::Base
  has_many :lesson_words
  has_many :answers, dependent: :destroy
  belongs_to :category

  accepts_nested_attributes_for :answers, reject_if:
    lambda {|a| a[:content].blank?}, allow_destroy: true

  validates :content, presence: true
  validates :category, presence: true
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < AdminController
  def index
    @words = Word.paginate page: params[:page], per_page: 10
  end

  def show
    @word = Word.find params[:id]
    @word_answers = @word.answers
  end

  def new
    @categories = Category.all
    @word = Word.new
    4.times {@word.answers.build}
  end

  def create
    @word = Word.new word_params
    if @word.save
      redirect_to admin_words_path
    else
      render "new"
    end
  end

  def edit
    @word = Word.find params[:id]
    @categories = Category.all
  end

  def update
    @word = Word.find params[:id]

    if @word.update_attributes word_params
      redirect_to admin_words_path
    else
      render "edit"
    end
  end

  def destroy
    @word = Word.find params[:id]
    @word.destroy

    redirect_to admin_words_path
  end

  private
  def word_params
    params.require(:word).permit :content, :category_id,
      answers_attributes: [:id, :word_id, :content, :correct, :_destroy]
  end
end

app/views/admin/words/_answer_fields.html.erb
<div class="form-group fields">
  <%= f.hidden_field :id %>
  <%= f.label :content, t(".answer"), class: "col-sm-2 control-label" %>
  <div class="col-sm-4">
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <%= f.label :correct, class: "col-sm-2 control-label" %>
  <div class="col-sm-2">
    <%= f.check_box :correct, class: "form-control" %>
  </div>
  <div class="col-sm-2">
    <%= f.hidden_field :_destroy, class: "removable" %>
    <%= link_to_remove_fields t(".remove"), f, "btn btn-danger" %>
  </div>
</div>

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word], html: {multipart: true,
  class: "form-horizontal style-form"} do |f| %>
  <div class="form-group">
    <%= f.label :content, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :content, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category_id, "Category", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :category_id, @categories, :id, :name,
        {prompt: "Select a category"}, {class: "form-control"} %>
    </div>
  </div>
  <%= t ".list_of_answers" %>
  <%= f.fields_for :answers do |builder| %>
    <%= render "answer_fields", f: builder %>
  <% end %>
  <div class="added-answer"></div>
  <%= link_to_add_fields t(".add_answer"), f, :answers,
    "btn btn-primary add-remove-answer", t(".add_new_answer") %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.submit class: "btn btn-success pull-right" %>
    </div>
  </div>
<% end %>

app/views/admin/words/_show_answers.html.erb
<b><%= t ".list" %></b>
<table class="table table-striped table-advance table-hover">
  <tbody>
    <% @word_answers.each do |answer| %>
      <tr>
        <td>
          <%= answer.content %>
        </td>
        <td>
          <% if answer.correct? %>
            <%= t ".correct" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/words/edit.html.erb
<section class="wrapper">
  <h3>
    <%= link_to admin_words_path do %>
      <i class="fa fa-angle-right">
        <%= t ".title" %>
      </i>
    <% end %>
  </h3>
  <div class="row mt">
    <div class="col-lg-12">
      <div class="form-panel top_line">
        <div class="form-header">
          <i class="fa fa-angle-right"></i>
          <%= t ".title" %>
        </div>
        <%= render "form" %>
      </div>
    </div>
  </div>
</section>

app/views/admin/words/index.html.erb
<section class="wrapper">
  <h3>
    <i class="fa fa-angle-right">
      <%= t ".title" %>
    </i>
  </h3>
  <div class="row mt">
    <div class="content-panel">
      <%= link_to new_admin_word_path, class: "btn btn-success btn-xs
        pull-right btn-panel" do %>
        <i class="fa fa-plus-circle">
          <%= t ".add" %>
        </i>
      <% end %>
      <table class="table table-striped table-advance table-hover">
        <h4>
          <i class="fa fa-angle-right">
            <%= t ".list" %>
          </i>
        </h4>
        <hr>
        <thead>
          <tr>
            <th>
              <i class="fa fa-text-height">
                <%= t ".content" %>
              </i>
            </th>
            <th>
              <i class="fa fa-text-height">
                <%= t ".content_category" %>
              </i>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @words.each do |word| %>
            <tr>
              <td>
                <%= word.content %>
              </td>
              <td>
                <%= word.category.name %>
              </td>
              <td>
                <div class="admin-actions">
                  <%= link_to admin_word_path(word), class: "button btn btn-success btn-xs" do %>
                    <i class="fa fa-file-text"></i>
                  <% end %>
                  <%= link_to edit_admin_word_path(word), class: "button btn btn-primary btn-xs" do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                  <%= link_to admin_word_path(word), method: :delete,
                    data: {confirm: "You want to delete?"},class: "button btn btn-danger btn-xs" do %>
                    <i class="fa fa-trash-o"></i>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @words %>
    </div>
  </div>
</section>

app/views/admin/words/new.html.erb
<section class="wrapper">
  <h3>
    <%= link_to admin_words_path do %>
      <i class="fa fa-angle-right">
        <%= t ".title" %>
      </i>
    <% end %>
  </h3>
  <div class="row mt">
    <div class="col-lg-12">
      <div class="form-panel top_line">
        <div class="form-header">
          <i class="fa fa-angle-right"></i>
          <%= t ".title" %>
        </div>
        <%= render "form" %>
      </div>
    </div>
  </div>
</section>

app/views/admin/words/show.html.erb
<section class="wrapper">
  <h3>
    <%= link_to admin_words_path do %>
      <i class="fa fa-angle-right">
        <%= t ".title" %>
      </i>
    <% end %>
  </h3>
  <div class="row mt">
    <div class="col-md-9">
      <section>
        <div class="panel-heading">
          <div class="pull-left">
            <h5>
              <i class="fa fa-tasks">
              </i>
            </h5>
          </div>
        </div>
        <div class="panel-body">
          <div>
            <ul>
              <li>
                <label class="bold">
                  <%= t ".content" %>
                </label>
                <span>
                  <%= @word.content %>
                </span>
              </li>
              <li>
                <label class="bold">
                  <%= t ".content_category" %>
                </label>
                <span>
                  <%= @word.category.name %>
                </span>
              </li>
            </ul>
            <%= render "show_answers" %>
          </div>
          <div class="add-task-row">
            <%= link_to t(".edit"), edit_admin_word_path(@word),
              class: "btn btn-success btn-sm pull-left" %>
            <%= link_to t(".add"), new_admin_word_path(@word),
              class: "btn btn-default btn-sm pull-right" %>
          </div>
        </div>
      </section>
    </div>
  </div>
</section>