config/routes.rb
Rails.application.routes.draw do

  root    "home#index"
  get     "about"       => "home#about", as: "about"
  get     "words"       => "words#index", as: "words"
  get     "signup"      => "users#new"
  get     "login"       => "sessions#new"
  get     "/results/:id", to: "results#show", as: "result"
  post    "login"       => "sessions#create"
  delete  "logout"      => "sessions#destroy"

  resources :users do
    member do
      resources :relationships, only: [:index, :create, :destroy]
    end
  end
  resources :categories
  resources :lessons
  resources :lesson_words
  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :words
    resources :answers
    resources :users
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      @activities = current_user.feeds.paginate page: params[:page], per_page: 15
    end
  end
end

app/views/home/_signup.html.erb
<div class ="page-wrapper">
  <div class="center jumbotron">
    <h1><%= t ".signup_welcome" %></h1>
    <h2><%= t ".signup_description" %>  </h2>
    <%= link_to t(".signup_button"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/home/about.html.erb
<div class ="page-wrapper">
  <div class="center jumbotron">
    <h1><%= t ".about_desc" %></h1>
    <h2><%= t ".about_text" %>  </h2>
  </div>
</div>

app/views/home/index.html.erb
<% if logged_in? %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <%= t ".panel_title" %>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <div class="row user-profile">
            <%= link_to image_tag(current_user.avatar, size: "150x150"), current_user %>
          </div>
          <div class="row user-profile">
            <%= current_user.full_name %>
          </div>
          <div class="row user-profile">
            <%= render "shared/status" %>
            <%= render "shared/follow_form" %>
          </div>
        </div>
        <div class="col-md-8">
          <div class="row">
            <%= link_to t(".button_words"), words_path, class: "btn btn-primary btn-lg" %>
            <%= link_to t(".button_lessons"), categories_path, class: "btn btn-primary btn-lg" %>
          </div>
          <div class="row">
            <h3><%= t ".activities" %></h3>
            <ul>
              <% @activities.each do |activity| %>
                <li>
                  <%= link_to image_tag(activity.log.avatar, size: "50x50"), activity.log %>
                  <%= link_to activity.log.full_name, activity.log %>
                  <div class="activity-content">
                    <%= activity.content %>
                  </div>
                </li>
                <hr>
                <%= will_paginate @activities %>
              <% end %>
            </ul>
          </div>
        </div>
    </div>
  </div>
<% else %>
  <%= render "signup" %>
<% end%>