config/routes.rb
Rails.application.routes.draw do

  root    "home#index"
  get     "about"       => "home#about", as: "about"
  get     "words"       => "words#index", as: "words"
  get     "signup"      => "users#new"
  get     "login"       => "sessions#new"
  get     "/results/:id", to: "results#show", as: "result"
  post    "login"       => "sessions#create"
  delete  "logout"      => "sessions#destroy"

  resources :users do
    member do
      resources :relationships, only: [:index, :create, :destroy]
    end
  end
  resources :categories
  resources :lessons
  resources :lesson_words
  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :words
    resources :answers
    resources :users
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons
  has_many :words
  validates :name, :description, presence: true
  mount_uploader :picture, PictureUploader
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    @categories = Category.order(created_at: :desc)
      .paginate page: params[:page], per_page: 5
  end

  def new
    @category = Category.new
  end

  def destroy
    @categories = Category.find params[:id]
    @categories.destroy
    redirect_to admin_categories_path
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".create_successful"
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t ".create_invalid"
      render :new
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes category_params
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def show
    @category = Category.find params[:id]
  end

  private
  def category_params
    params.require(:category).permit :name, :description, :picture
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/views/categories/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= t ".panel_title" %>
  </div>
  <div class="panel-body">
    <% @categories.each do |cat| %>
      <% if cat.id % 2 == 0 %>
        <div class="row category">
          <div class="col-md-6 category-picture">
            <%= image_tag cat.picture, size: "350x150" %>
          </div>
          <div class="col-md-6">
            <h3>
              <b><%= cat.name %></b>
            </h3>
            <br>
            <%= cat.description%>
            <br>
            <%= link_to t(".start"), lessons_path(category_id: cat.id), method: :post, class: "btn btn-success" %>
          </div>
        </div>
      <% else %>
        <div class="row category">
          <div class="col-md-6">
            <h3>
              <b><%= cat.name %></b>
            </h3>
            <br>
            <%= cat.description%>
            <br>
            <%= link_to t(".start"), lessons_path(category_id: cat.id), method: :post, class: "btn btn-success" %>
          </div>
          <div class="col-md-6 category-picture">
            <%= image_tag cat.picture, size: "350x150" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>