config/routes.rb
Rails.application.routes.draw do

  root    "home#index"
  get     "about"       => "home#about", as: "about"
  get     "words"       => "words#index", as: "words"
  get     "signup"      => "users#new"
  get     "login"       => "sessions#new"
  get     "/results/:id", to: "results#show", as: "result"
  post    "login"       => "sessions#create"
  delete  "logout"      => "sessions#destroy"

  resources :users do
    member do
      resources :relationships, only: [:index, :create, :destroy]
    end
  end
  resources :categories
  resources :lessons
  resources :lesson_words
  resources :account_activations, only: [:edit]
  resources :relationships,       only: [:create, :destroy]

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :words
    resources :answers
    resources :users
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_accessor :remember_token, :activation_token

  has_many :lessons, dependent: :destroy
  has_many :activities, as: :log
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id,
    dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id,
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  mount_uploader :avatar, AvatarUploader
  validates :first_name, presence: true, length: {maximum: 50}
  validates :last_name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 50},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  before_save   :downcase_email
  before_create :create_activation_digest

  def full_name
    "#{first_name} #{last_name}"
  end

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create string, cost: cost
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def authenticated? attribute, token
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def feeds
    following_ids = self.active_relationships.pluck :followed_id
    following_ids << id
    Activity.followed following_ids
  end

  def total_words_learned
    @total_learned = []
    lessons.map{|lesson|
      lesson.list_of_correct_answer.map{|lesson_word|
        @total_learned << lesson_word.word_id
      }
    }
    @total_learned.uniq.count
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  private
  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.paginate page: params[:page], per_page: 10
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]

    if @user.update_attributes user_params
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy

    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit :first_name, :last_name, :email,
      :password, :password_confirmation, :avatar, :admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate page: params[:page], per_page: 20
  end

  def show
    @user = User.find params[:id]
    @activities = @user.activities.paginate page: params[:page], per_page: 15
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      @user.send_activation_email
      flash[:info] = t ".info"
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]

    if @user.update_attributes user_params
      flash[:success] = t ".success"
      redirect_to @user
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit :first_name, :last_name, :email,
      :password, :password_confirmation, :avatar
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], html: {multipart: true,
  class: "form-horizontal style-form"} do |f| %>
  <div class="form-group">
    <%= f.label :first_name, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :admin, class: "col-md-2 control-label" %>
    <div class="col-md-10">
      <%= f.check_box :admin, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-12">
      <%= f.file_field :avatar, accept: "image/jpeg,image/gif,image/png" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-12">
      <%= f.submit class: "btn btn-success pull-right" %>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<section class="wrapper">
  <h3>
    <%= link_to admin_users_path do %>
      <i class="fa fa-angle-right">
        <%= t ".title" %>
      </i>
    <% end %>
  </h3>
  <div class="row mt">
    <div class="col-lg-12">
      <div class="form-panel top_line">
        <div class="form-header">
          <i class="fa fa-angle-right"></i>
          <%= t ".title" %>
        </div>
        <%= render "form" %>
      </div>
    </div>
  </div>
</section>

app/views/admin/users/index.html.erb
<section class="wrapper">
  <h3>
    <i class="fa fa-angle-right">
      <%= t ".title" %>
    </i>
  </h3>
  <div class="row mt">
    <div class="content-panel">
      <%= link_to new_admin_user_path, class: "btn btn-success btn-xs
        pull-right btn-panel" do %>
        <i class="fa fa-plus-circle">
          <%= t ".add" %>
        </i>
      <% end %>
      <table class="table table-striped table-advance table-hover">
        <h4>
          <i class="fa fa-angle-right">
            <%= t ".list" %>
          </i>
        </h4>
        <hr>
        <thead>
          <tr>
            <th>
              <i class="fa fa-text-height">
                <%= t ".name" %>
              </i>
            </th>
            <th>
              <i class="fa fa-text-height">
                <%= t ".email" %>
              </i>
            </th>
            <th>
              <i class="fa fa-text-height">
                <%= t ".admin" %>
              </i>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= user.full_name %>
              </td>
              <td>
                <%= user.email %>
              </td>
              <td>
                <%= user.admin? %>
              </td>
              <td>
                <div class="admin-actions">
                  <%= link_to admin_user_path(user), class: "button btn btn-success btn-xs" do %>
                    <i class="fa fa-file-text"></i>
                  <% end %>
                  <%= link_to edit_admin_user_path(user), class: "button btn btn-primary btn-xs" do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                  <%= link_to admin_user_path(user), method: :delete,
                    data: {confirm: "You want to delete?"},class: "button btn btn-danger btn-xs" do %>
                    <i class="fa fa-trash-o"></i>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @users %>
    </div>
  </div>
</section>

app/views/admin/users/new.html.erb
<section class="wrapper">
  <h3>
    <%= link_to admin_users_path do %>
      <i class="fa fa-angle-right">
        <%= t ".title" %>
      </i>
    <% end %>
  </h3>
  <div class="row mt">
    <div class="col-lg-12">
      <div class="form-panel top_line">
        <div class="form-header">
          <i class="fa fa-angle-right"></i>
          <%= t ".title" %>
        </div>
        <%= render "form" %>
      </div>
    </div>
  </div>
</section>

app/views/admin/users/show.html.erb
<section class="wrapper">
  <h3>
    <%= link_to admin_users_path do %>
      <i class="fa fa-angle-right">
        <%= t ".title" %>
      </i>
    <% end %>
  </h3>
  <div class="row mt">
    <div class="col-md-9">
      <section>
        <div class="panel-heading">
          <div class="pull-left">
            <h5>
              <i class="fa fa-tasks">
              </i>
            </h5>
          </div>
        </div>
        <div class="panel-body">
          <div>
            <ul>
              <li>
                <%= image_tag @user.avatar, size: "150x150" %>
              </li>
              <li>
                <label class="bold">
                  <%= t ".name" %>
                </label>
                <span>
                  <%= @user.full_name %>
                </span>
              </li>
              <li>
                <label class="bold">
                  <%= t ".email" %>
                </label>
                <span>
                  <%= @user.email %>
                </span>
              </li>
              <li>
                <label class="bold">
                  <%= t ".admin" %>
                </label>
                <span>
                  <%= @user.admin? %>
                </span>
              </li>
            </ul>
          </div>
          <div class="add-task-row">
            <%= link_to t(".edit"), edit_admin_user_path(@user),
              class: "btn btn-success btn-sm pull-left" %>
            <%= link_to t(".add"), new_admin_user_path(@user),
              class: "btn btn-default btn-sm pull-right" %>
          </div>
        </div>
      </section>
    </div>
  </div>
</section>